//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelToAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ievietoju jaunās vērtības Microsoft Access tabulā....
        /// </summary>
        internal static string AccessInsert {
            get {
                return ResourceManager.GetString("AccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās ievietot jaunās vērtības Microsoft Access!.
        /// </summary>
        internal static string AccessInsertFailed {
            get {
                return ResourceManager.GetString("AccessInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access datnes atrašanās vieta.
        /// </summary>
        internal static string AccessPath {
            get {
                return ResourceManager.GetString("AccessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izpildu Microsoft Access Query....
        /// </summary>
        internal static string AccessQuery {
            get {
                return ResourceManager.GetString("AccessQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās izpildīt Microsoft Access Query!.
        /// </summary>
        internal static string AccessQueryFailed {
            get {
                return ResourceManager.GetString("AccessQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu ievadīji eksistējošu Microsoft Access Tabulu!.
        /// </summary>
        internal static string AccessQueryTip {
            get {
                return ResourceManager.GetString("AccessQueryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vērtības veiksmīgi ievietotas Microsoft Access..
        /// </summary>
        internal static string AccessSuccess {
            get {
                return ResourceManager.GetString("AccessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veidoju jaunu Microsoft Access tabulu....
        /// </summary>
        internal static string AccessTable {
            get {
                return ResourceManager.GetString("AccessTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidotā Microsoft Access tabula ir izdzēsta..
        /// </summary>
        internal static string AccessTableDel {
            get {
                return ResourceManager.GetString("AccessTableDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izdzēšu Microsoft Access izveidoto tabulu....
        /// </summary>
        internal static string AccessTableDelete {
            get {
                return ResourceManager.GetString("AccessTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās izdzēst Microsoft Access izveidoto tabulu!.
        /// </summary>
        internal static string AccessTableDeleteFailed {
            get {
                return ResourceManager.GetString("AccessTableDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās izveidot jaunu Microsoft Access tabulu!.
        /// </summary>
        internal static string AccessTableFailed {
            get {
                return ResourceManager.GetString("AccessTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AccessTip {
            get {
                object obj = ResourceManager.GetObject("AccessTip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pārlūkot.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pārbaudu ievadītās vērtības....
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvēlies Datni.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veidoju savienojumu ar Microsoft Access....
        /// </summary>
        internal static string ConnectingAccess {
            get {
                return ResourceManager.GetString("ConnectingAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās savienoties ar Microsoft Access!.
        /// </summary>
        internal static string ConnectingAccessFailed {
            get {
                return ResourceManager.GetString("ConnectingAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veidoju savienojumu ar Microsoft Excel....
        /// </summary>
        internal static string ConnectingExcel {
            get {
                return ResourceManager.GetString("ConnectingExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās savienoties ar Microsoft Excel!.
        /// </summary>
        internal static string ConnectingExcelFailed {
            get {
                return ResourceManager.GetString("ConnectingExcelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu neievadīji Microsoft Access datnes atrašanās vietu!.
        /// </summary>
        internal static string EnterAccess {
            get {
                return ResourceManager.GetString("EnterAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu neievadīji Microsoft Excel datnes atrašanās vietu!.
        /// </summary>
        internal static string EnterExcel {
            get {
                return ResourceManager.GetString("EnterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu neievadīji Microsoft Excel DarbaGrāmatu!.
        /// </summary>
        internal static string EnterSheet {
            get {
                return ResourceManager.GetString("EnterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu neievadīji Microsoft Access Tabulu!.
        /// </summary>
        internal static string EnterTable {
            get {
                return ResourceManager.GetString("EnterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vērtību lauks.
        /// </summary>
        internal static string ExcelField {
            get {
                return ResourceManager.GetString("ExcelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel vērtības ir nolasītas..
        /// </summary>
        internal static string ExcelFinished {
            get {
                return ResourceManager.GetString("ExcelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel datnes atrašanās vieta.
        /// </summary>
        internal static string ExcelPath {
            get {
                return ResourceManager.GetString("ExcelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izpildu Microsoft Excel Query....
        /// </summary>
        internal static string ExcelQuery {
            get {
                return ResourceManager.GetString("ExcelQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās izpildīt Microsoft Excel Query!.
        /// </summary>
        internal static string ExcelQueryFailed {
            get {
                return ResourceManager.GetString("ExcelQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu ievadīji nēeksistējošu Microsoft Excel DarbaGrāmatu!.
        /// </summary>
        internal static string ExcelQueryTip {
            get {
                return ResourceManager.GetString("ExcelQueryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolasu Microsoft Excel vērtības....
        /// </summary>
        internal static string ExcelRead {
            get {
                return ResourceManager.GetString("ExcelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolasu Microsoft Excel kolonnas....
        /// </summary>
        internal static string ExcelReadCol {
            get {
                return ResourceManager.GetString("ExcelReadCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelTip {
            get {
                object obj = ResourceManager.GetObject("ExcelTip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelTip2 {
            get {
                object obj = ResourceManager.GetObject("ExcelTip2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelTip3 {
            get {
                object obj = ResourceManager.GetObject("ExcelTip3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lūdzu ievadi pareizas vērtības!.
        /// </summary>
        internal static string FieldsEnter {
            get {
                return ResourceManager.GetString("FieldsEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertības ir pārbaudītas, bet dažas ir nepareizas!.
        /// </summary>
        internal static string FieldsNotValid {
            get {
                return ResourceManager.GetString("FieldsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertības ir pārbaudītas un ir pareizas..
        /// </summary>
        internal static string FieldsValid {
            get {
                return ResourceManager.GetString("FieldsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nēeksistē!.
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Access datne.
        /// </summary>
        internal static string FileMDB {
            get {
                return ResourceManager.GetString("FileMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel datne.
        /// </summary>
        internal static string FileXLS {
            get {
                return ResourceManager.GetString("FileXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nav pareiza!.
        /// </summary>
        internal static string NotRight {
            get {
                return ResourceManager.GetString("NotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apstiprināt.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pievienot AutoNumber un Primary Key.
        /// </summary>
        internal static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norādītajā Darbagrāmatā nav nevienas vērtības!.
        /// </summary>
        internal static string SheetEmpty {
            get {
                return ResourceManager.GetString("SheetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norādītā Darbagrāmata nēeksistē!.
        /// </summary>
        internal static string SheetExist {
            get {
                return ResourceManager.GetString("SheetExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabula.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaidu.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Excel To Access.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarbaGrāmata.
        /// </summary>
        internal static string WorkSheet {
            get {
                return ResourceManager.GetString("WorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu ievadīji nepareizu Microsoft Excel vērtību lauku!.
        /// </summary>
        internal static string WrongExcelField {
            get {
                return ResourceManager.GetString("WrongExcelField", resourceCulture);
            }
        }
    }
}
